require_relative 'generator/template'
require_relative 'generator/page'
require_relative 'generator/index'
require_relative 'generator/maker'
require_relative 'generator/model'
require_relative 'generator/engine'
